# Basic Numpy Function

## Subhamay Dhara

In [2]:
import numpy as np

In [3]:
a = np.arange(5)

In [4]:
a

array([0, 1, 2, 3, 4])

In [8]:
b = np.array([1,2,3,4,5,6,7,8,9]) #one dimensional array

In [9]:
b

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [10]:
a[0]

0

In [14]:
c = np.array([[1,2,3],[4,5,6],[7,8,9]]) #three dimensional array

In [15]:
c

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [16]:
a = np.arange(20)

In [17]:
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [18]:
b = a.reshape(4,5)  #reshape the array

In [19]:
b

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [21]:
b.ndim

2

In [22]:
b.shape

(4, 5)

In [23]:
b.size

20

In [24]:
b.dtype.name

'int32'

In [25]:
b.itemsize

4

In [26]:
np.array([[1,2],[3,4]], dtype= complex)

array([[1.+0.j, 2.+0.j],
       [3.+0.j, 4.+0.j]])

In [27]:
np.array([[complex(1,1), complex(1,2)],[3,4]], dtype = complex)

array([[1.+1.j, 1.+2.j],
       [3.+0.j, 4.+0.j]])

In [28]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [29]:
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [30]:
np.empty((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [32]:
np.linspace(1,3,9)

array([1.  , 1.25, 1.5 , 1.75, 2.  , 2.25, 2.5 , 2.75, 3.  ])

In [33]:
np.ones(2,dtype=np.int64)

array([1, 1], dtype=int64)

In [37]:
random_int = np.random.randint(low = 5, high = 100, size = (6))  #random integer
print(random_int)

[87 44 42 32 16 15]


In [40]:
float_random = np.random.random([6])   #random float

In [41]:
print(float_random)

[0.69124542 0.79705837 0.8316288  0.84845938 0.4008646  0.73017636]


In [42]:
a = np.array([1,2,5,9,3,6,4])

In [43]:
np.sort(a)

array([1, 2, 3, 4, 5, 6, 9])

In [44]:
b = np.array([1,2,3,4])

In [45]:
c= np.array([5,6,7,8])

In [47]:
d = np.concatenate((b,c))

In [48]:
d

array([1, 2, 3, 4, 5, 6, 7, 8])

In [49]:
x= np.array([[1,2,3],[4,5,6]])
y= np.array([[7,8,9]])

In [51]:
np.concatenate((x,y), axis=0)                                                                                                                                                                                                                                                                                                                                                                                                   

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [52]:
a = np.array([1,4,6,8])

In [53]:
a.sum()

19

In [57]:
b= np.array([[1,2,3],[4,5,6],[7,8,9]])

In [58]:
b

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [59]:
b.sum(axis=0)

array([12, 15, 18])

In [60]:
b.sum(axis=1)

array([ 6, 15, 24])

In [61]:
data = np.array([1.0, 2.0])

In [62]:
data*1.5

array([1.5, 3. ])

In [72]:
n = np.arange(10)**2
print(n)

[ 0  1  4  9 16 25 36 49 64 81]


In [73]:
n[0]

0

In [74]:
n[-1]

81

In [75]:
n[5]

25

In [76]:
n1 = n[1:5]

In [77]:
n1

array([ 1,  4,  9, 16], dtype=int32)

In [78]:
n2 = n[0:6:2]

In [79]:
n2

array([ 0,  4, 16], dtype=int32)

In [80]:
a = np.array([[1,3,5], [2,7,4]])

In [81]:
bool_index = a>2

In [82]:
bool_index

array([[False,  True,  True],
       [False,  True,  True]])

In [83]:
print(a[a>2])

[3 5 7 4]


In [84]:
b = np.array([-1,2,-3,-4])

In [87]:
b[b<0] += 10

In [88]:
b

array([9, 2, 7, 6])

In [89]:
c = np.arange(10)

In [90]:
np.where(c<5, c ,10*c)

array([ 0,  1,  2,  3,  4, 50, 60, 70, 80, 90])